-- Add display_name column to profiles if it doesn't exist
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS display_name text;

-- Drop the old results table if it exists (this will delete existing data!)
DROP TABLE IF EXISTS results;

-- Create the new results table with all the required fields
CREATE TABLE results (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users,
  display_name text not null,
  wpm numeric not null,
  accuracy numeric not null,
  mode text not null,
  difficulty text not null,
  case_mode text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up RLS for results
ALTER TABLE results ENABLE ROW LEVEL SECURITY;

-- Drop old policies if they exist
DROP POLICY IF EXISTS "Results are viewable by everyone." ON results;
DROP POLICY IF EXISTS "Anyone can insert results." ON results;

-- Create new policies
CREATE POLICY "Results are viewable by everyone."
  ON results FOR SELECT
  USING ( true );

CREATE POLICY "Anyone can insert results."
  ON results FOR INSERT
  WITH CHECK ( true );
