-- Create a table for public profiles
create table profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  avatar_url text,
  website text,

  constraint username_length check (char_length(username) >= 3)
);

-- Set up Row Level Security (RLS)
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Create a table for typing test results
create table results (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  wpm numeric not null,
  accuracy numeric not null,
  mode text not null, -- '15', '30', '60' etc.
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up RLS for results
alter table results enable row level security;

create policy "Results are viewable by everyone."
  on results for select
  using ( true );

create policy "Users can insert their own results."
  on results for insert
  with check ( auth.uid() = user_id );

-- Create a function to handle new user creation
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger the function every time a user is created
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
